version: "3"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: omeka
      MYSQL_DATABASE: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
  neatline:
    build: .
    ports:
      - "8880:80"
    links:
      - mysql
    environment:
      MYSQL_DBNAME: omeka
      MYSQL_USER: omeka
      MYSQL_PASSWORD: omeka
    volumes:
      - ./Neatline:/app/Omeka/plugins/Neatline
      - ./NeatlineSIMILE:/app/Omeka/plugins/NeatlineSIMILE
      - ./NeatlineText:/app/Omeka/plugins/NeatlineText
      - ./NeatlineTime:/app/Omeka/plugins/NeatlineTime
      - ./NeatlineWaypoints:/app/Omeka/plugins/NeatlineWaypoints

volumes:
  Neatline:
  NeatlineSIMILE:
  NeatlineText:
  NeatlineTime:
  NeatlineWaypoints:
